/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.apono.sdk.model

import io.apono.sdk.model.TagModelV3

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param integrationId 
 * @param resourceType 
 * @param resourceTagMatchers 
 * @param permissions 
 */


data class AccessTargetModelV3 (

    @field:JsonProperty("integration_id")
    val integrationId: kotlin.String,

    @field:JsonProperty("resource_type")
    val resourceType: kotlin.String,

    @field:JsonProperty("resource_tag_matchers")
    val resourceTagMatchers: kotlin.collections.List<TagModelV3>,

    @field:JsonProperty("permissions")
    val permissions: kotlin.collections.List<kotlin.String>

)

