/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.apono.sdk.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * Values: PENDING,APPROVED,REJECTED,GRANTED,REVOKING,EXPIRED,FAILED
 */

enum class AccessStatusModel(val value: kotlin.String) {

    @JsonProperty(value = "PENDING")
    PENDING("PENDING"),

    @JsonProperty(value = "APPROVED")
    APPROVED("APPROVED"),

    @JsonProperty(value = "REJECTED")
    REJECTED("REJECTED"),

    @JsonProperty(value = "GRANTED")
    GRANTED("GRANTED"),

    @JsonProperty(value = "REVOKING")
    REVOKING("REVOKING"),

    @JsonProperty(value = "EXPIRED")
    EXPIRED("EXPIRED"),

    @JsonProperty(value = "FAILED")
    FAILED("FAILED");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is AccessStatusModel) "$data" else null

        /**
         * Returns a valid [AccessStatusModel] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AccessStatusModel? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

