/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.apono.sdk.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param userId 
 * @param integrationId 
 * @param resourceIds 
 * @param permissions 
 * @param justification 
 */


data class CreateAccessRequest (

    @field:JsonProperty("user_id")
    val userId: kotlin.String,

    @field:JsonProperty("integration_id")
    val integrationId: kotlin.String,

    @field:JsonProperty("resource_ids")
    val resourceIds: kotlin.collections.List<kotlin.String>,

    @field:JsonProperty("permissions")
    val permissions: kotlin.collections.List<kotlin.String>,

    @field:JsonProperty("justification")
    val justification: kotlin.String

)

