/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.apono.sdk.model

import io.apono.sdk.model.AccessFlowModelV3Timeframe
import io.apono.sdk.model.AccessTargetModelV3
import io.apono.sdk.model.ApproverModel
import io.apono.sdk.model.GranteeModel
import io.apono.sdk.model.TriggerType

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param name 
 * @param active 
 * @param triggerType 
 * @param grantees 
 * @param accessTargets 
 * @param approvers 
 * @param revokeAfterInSec 
 * @param justificationRequired 
 * @param timeframe 
 */


data class CreateAccessFlowRequestV3 (

    @field:JsonProperty("name")
    val name: kotlin.String,

    @field:JsonProperty("active")
    val active: kotlin.Boolean,

    @field:JsonProperty("trigger_type")
    val triggerType: TriggerType,

    @field:JsonProperty("grantees")
    val grantees: kotlin.collections.List<GranteeModel>,

    @field:JsonProperty("access_targets")
    val accessTargets: kotlin.collections.List<AccessTargetModelV3>,

    @field:JsonProperty("approvers")
    val approvers: kotlin.collections.List<ApproverModel>,

    @field:JsonProperty("revoke_after_in_sec")
    val revokeAfterInSec: kotlin.Int,

    @field:JsonProperty("justification_required")
    val justificationRequired: kotlin.Boolean,

    @field:JsonProperty("timeframe")
    val timeframe: AccessFlowModelV3Timeframe? = null

)

