/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.apono.sdk.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * Values: MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY
 */

enum class DayOfWeek(val value: kotlin.String) {

    @JsonProperty(value = "MONDAY")
    MONDAY("MONDAY"),

    @JsonProperty(value = "TUESDAY")
    TUESDAY("TUESDAY"),

    @JsonProperty(value = "WEDNESDAY")
    WEDNESDAY("WEDNESDAY"),

    @JsonProperty(value = "THURSDAY")
    THURSDAY("THURSDAY"),

    @JsonProperty(value = "FRIDAY")
    FRIDAY("FRIDAY"),

    @JsonProperty(value = "SATURDAY")
    SATURDAY("SATURDAY"),

    @JsonProperty(value = "SUNDAY")
    SUNDAY("SUNDAY");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is DayOfWeek) "$data" else null

        /**
         * Returns a valid [DayOfWeek] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): DayOfWeek? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

