/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.apono.sdk.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * Values: Resource,ResourceIntegration,User,Group,ContextAttribute,Permissions,Metadata,AccessFlowName
 */

enum class FilterResultContextType(val value: kotlin.String) {

    @JsonProperty(value = "Resource")
    Resource("Resource"),

    @JsonProperty(value = "ResourceIntegration")
    ResourceIntegration("ResourceIntegration"),

    @JsonProperty(value = "User")
    User("User"),

    @JsonProperty(value = "Group")
    Group("Group"),

    @JsonProperty(value = "ContextAttribute")
    ContextAttribute("ContextAttribute"),

    @JsonProperty(value = "Permissions")
    Permissions("Permissions"),

    @JsonProperty(value = "Metadata")
    Metadata("Metadata"),

    @JsonProperty(value = "AccessFlowName")
    AccessFlowName("AccessFlowName");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is FilterResultContextType) "$data" else null

        /**
         * Returns a valid [FilterResultContextType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): FilterResultContextType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

