/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.apono.sdk.model

import io.apono.sdk.model.FilterResultContext
import io.apono.sdk.model.FilterResultContextType

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param context 
 * @param filterPhrase 
 * @param matchedValues 
 * @param type 
 */


data class FilterResult (

    @field:JsonProperty("context")
    val context: FilterResultContext,

    @field:JsonProperty("filter_phrase")
    val filterPhrase: kotlin.String,

    @field:JsonProperty("matched_values")
    val matchedValues: kotlin.collections.List<kotlin.String>,

    @field:JsonProperty("type")
    val type: FilterResultContextType

)

