/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.apono.sdk.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * Values: USER,GROUP,EXTERNAL_EMAIL,CONTEXT_ATTRIBUTE
 */

enum class GranteeTypeModel(val value: kotlin.String) {

    @JsonProperty(value = "USER")
    USER("USER"),

    @JsonProperty(value = "GROUP")
    GROUP("GROUP"),

    @JsonProperty(value = "EXTERNAL_EMAIL")
    EXTERNAL_EMAIL("EXTERNAL_EMAIL"),

    @JsonProperty(value = "CONTEXT_ATTRIBUTE")
    CONTEXT_ATTRIBUTE("CONTEXT_ATTRIBUTE");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is GranteeTypeModel) "$data" else null

        /**
         * Returns a valid [GranteeTypeModel] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): GranteeTypeModel? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

