/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.apono.sdk.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id 
 * @param label 
 * @param propertyValues 
 * @param default 
 */


data class IntegrationConfigParam (

    @field:JsonProperty("id")
    val id: kotlin.String,

    @field:JsonProperty("label")
    val label: kotlin.String,

    @field:JsonProperty("values")
    val propertyValues: kotlin.collections.List<kotlin.String>,

    @field:JsonProperty("default")
    val default: kotlin.String

)

