/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.apono.sdk.model

import io.apono.sdk.model.IntegrationConfigParam

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param name 
 * @param type 
 * @param description 
 * @param params 
 * @param requiresSecret 
 * @param supportedSecretTypes 
 */


data class IntegrationConfig (

    @field:JsonProperty("name")
    val name: kotlin.String,

    @field:JsonProperty("type")
    val type: kotlin.String,

    @field:JsonProperty("description")
    val description: kotlin.String,

    @field:JsonProperty("params")
    val params: kotlin.collections.List<IntegrationConfigParam>,

    @field:JsonProperty("requires_secret")
    val requiresSecret: kotlin.Boolean,

    @field:JsonProperty("supported_secret_types")
    val supportedSecretTypes: kotlin.collections.List<kotlin.String>

)

