/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.apono.sdk.model

import io.apono.sdk.model.IntegrationStatus

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id 
 * @param name 
 * @param type 
 * @param status 
 * @param metadata 
 * @param details 
 * @param provisionerId 
 * @param connection 
 * @param lastSyncTime 
 * @param secretConfig 
 */


data class Integration (

    @field:JsonProperty("id")
    val id: kotlin.String,

    @field:JsonProperty("name")
    val name: kotlin.String,

    @field:JsonProperty("type")
    val type: kotlin.String,

    @field:JsonProperty("status")
    val status: IntegrationStatus,

    @field:JsonProperty("metadata")
    val metadata: kotlin.Any,

    @field:JsonProperty("details")
    val details: kotlin.String? = null,

    @field:JsonProperty("provisioner_id")
    val provisionerId: kotlin.String? = null,

    @field:JsonProperty("connection")
    val connection: kotlin.Any? = null,

    @field:JsonProperty("last_sync_time")
    val lastSyncTime: kotlin.Double? = null,

    @field:JsonProperty("secret_config")
    val secretConfig: kotlin.Any? = null

)

