/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.apono.sdk.model

import io.apono.sdk.model.AccessFlowFilterResult
import io.apono.sdk.model.AccessFlowModelV3

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param `data` 
 * @param filterResult 
 */


data class PaginatedAccessFlowV3SearchResponse (

    @field:JsonProperty("data")
    val `data`: kotlin.collections.List<AccessFlowModelV3>,

    @field:JsonProperty("filter_result")
    val filterResult: kotlin.collections.List<AccessFlowFilterResult>? = null

)

