name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main, .*]
permissions:
  checks: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      MAVEN_CLI_OPTS: --batch-mode --no-transfer-progress
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0
      - name: Install JDK
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
        with:
          cache: 'maven'
          distribution: 'corretto'
          java-version-file: .java-version
      - name: Compile
        run: ./mvnw $MAVEN_CLI_OPTS clean compile
      - name: Unit Tests
        run: ./mvnw $MAVEN_CLI_OPTS test
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@f0b5d2433f350eff587831d4ad22cb15aab75866 # v2.8.0
        if: always()
        with:
          files: "*/target/surefire-reports/*.xml"
